{
    "name": "Gear On Rent",
    "version": "19.0.1.0.0",
    "author": "SmarterPeak",
    "license": "OEEL-1",
    "category": "Services/Rental",
    "website": "https://smarterpeak.com",
    "summary": "Rental and RMC blended production workflow with LOTO and NGT handling.",
    "depends": [
        "sale_management",
        "sale_renting",
        "project",
        "maintenance",
        "mrp",
        "account",
        "website",
        "helpdesk",
    ],
    "images": ["static/description/icon.png"],
    "data": [
        "data/sequence_data.xml",
        "data/security/gear_on_rent_security.xml",
        "data/security/ir.model.access.csv",
        "data/cron.xml",
        "data/product_rmc_data.xml",
        "views/gear_on_rent_templates.xml",
        "data/website_page_gear_on_rent.xml",
        "views/log_views.xml",
        "views/product_template_views.xml",
        "views/sale_order_views.xml",
        "views/workorder_views.xml",
        "views/rmc_work_order_views.xml",
        "views/menu.xml",
        "views/wizard_views.xml",
        "data/mail_templates.xml",
        "reports/qweb/report_daily_mo.xml",
        "reports/qweb/report_month_end.xml",
        "reports/qweb/report_invoice_templates.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
